### ISSUE TITLE
Error with example using OpenStreetMap

### ISSUE THREAD

**Issue by penproductions** [smeijer/L.GeoSearch#69]
I get this error when trying to load the example using OpenStreetMap. This is the default example. I can get the example to work when using Google.

`l.control.geosearch.js:153 XMLHttpRequest cannot load file://nominatim.openstreetmap.org/search?q=12%20galloway%20cres%20ontario&format=json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.L.Control.GeoSearch.L.Control.extend.sendRequest @ l.control.geosearch.js:153L.Control.GeoSearch.L.Control.extend.geosearch @ l.control.geosearch.js:103L.Control.GeoSearch.L.Control.extend._onKeyUp @ l.control.geosearch.js:233t.(anonymous function).a @ leaflet.js:7`

**Comment by Mithgol** [comment]
That's because `location.protocol` on [line 20](https://github.com/smeijer/L.GeoSearch/blob/e073626195200d3d524f50dcd00c24ccbc71b933/src/js/l.geosearch.provider.openstreetmap.js#L20) of `l.geosearch.provider.openstreetmap.js` becomes `'file'` if you load it by opening a HTML file (from your local filesystem) in a browser.

I guess that code has been intended to run always on a web server, never in a file.

**Comment by penproductions** [comment]
Thanks I will give that a try on my local server and see if I can get it running. 

Another question, which is better to run, the Google search or the OpenStreetMap? Is there an advantage of one over the other?

**Comment by Mithgol** [comment]
If you use OSM tiles, you'd better use OSM search because it has the same accuracy and the same details (streets, buildings, etc.).

**Comment by smeijer** [comment]
The file system issue is fixed in the latest version. Let me know if you have any other questions.

**Comment by Mithgol** [comment]
For future references, fixed in 52627401d5fccb048885286b52a2aa3251884eaa.
